-- create table with # in table name
create table tabl#e1 (c1 SMALLINT, c2 DATE);

-- create table with $ in table name
create table table1$ (c1 SMALLINT, c2 DATE);

-- create table with both $ & # in table name
create table tab#le1$ (c1 SMALLINT, c2 DATE);

-- create table with $ & # in column name
create table tab#le1$ (c#1 SMALLINT, c$2 DATE);

CREATE TABLE t1 (id NUMBER GENERATED AS IDENTITY);

CREATE TABLE t2 (id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10));

CREATE TABLE t3 (id NUMBER DEFAULT some_seq.NEXTVAL);

CREATE TABLE departments_demo
    ( department_id    NUMBER(4)   PRIMARY KEY ENABLE
    , department_name  VARCHAR2(30)
           CONSTRAINT  dept_name_nn  NOT NULL DISABLE
    , manager_id       NUMBER(6)
    , location_id      NUMBER(4)
    , dn               VARCHAR2(300)
    ) ;
