# sqlfluff is free to use to improve sql in whatever context you
# wish to use it.

# The BEST way to support sqlfluff if you can is to contribute TIME.
# sqlfluff is a community project which needs the community to contribute
# to if it's going to achieve its goals.
# See CONTRIBUTING.md for more details.

# If you'd like to contribute something, but your circumstances don't
# allow you to commit time, then financial support is always welcome.
# Anything you contribute will go toward supporting the project, either
# as a donation toward infrastructure and hosting costs, or to enable
# maintainers to spend more time on the project.

# For more details on how this money is used, see the GitHub sponsor
# page for sqlfluff at https://github.com/sponsors/sqlfluff.

github: sqlfluff
