ansi:
  - "/(ansi)/i"

athena:
  - "/(athena)/i"

bigquery:
  - "/(bigquery)/i"

clickhouse:
  - "/(clickhouse)/i"

databricks:
  - "/(databricks)/i"

db2:
  - "/(db2)/i"

duckdb:
  - "/(duckdb)/i"

exasol:
  - "/(exasol)/i"

greenplum:
  - "/(greenplum)/i"

hive:
  - "/(hive)/i"

materialize:
  - "/(materialize)/i"

mysql:
  - "/(mysql)/i"

oracle:
  - "/(oracle)/i"

postgres:
  - "/(postgres)/i"

redshift:
  - "/(redshift)/i"

snowflake:
  - "/(snowflake)/i"

soql:
  - "/(soql)/i"

sparksql:
  - "/(sparksql)/i"

sqlite:
  - "/(sqlite)/i"

t-sql:
  - "/(t-sql|tsql)/i"

teradata:
  - "/(teradata)/i"

trino:
  - "/(trino)/i"

vertica:
  - "/(vertica)/i"
