FROM python:3.9-slim-bullseye

RUN apt update \
&& apt -y install libpq-dev gcc
# Set separate working directory for easier debugging.
WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip pip install --upgrade pip setuptools wheel

# Install requirements separately
# to take advantage of layer caching.
COPY requirements*.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install --upgrade -r requirements_dev.txt

# Set up dbt-related dependencies.
RUN --mount=type=cache,target=/root/.cache/pip pip install dbt-postgres

# Copy everything. (Note: If needed, we can use .dockerignore to limit what's copied.)
COPY . .

# Install sqlfluff and the dbt templater in editable mode.
RUN pip install -e . -e plugins/sqlfluff-templater-dbt
