/* This is a generated file! */
use once_cell::sync::Lazy;
use crate::matcher::{LexMatcher, extract_nested_block_comment};
use crate::token::Token;
use crate::regex::RegexModeGroup;
use crate::dialect::Dialect;

pub static SNOWFLAKE_KEYWORDS: Lazy<Vec<String>> = Lazy::new(|| { vec![
    "ALL".to_string(),
    "ALTER".to_string(),
    "AND".to_string(),
    "ANY".to_string(),
    "AS".to_string(),
    "ASOF".to_string(),
    "BEARER".to_string(),
    "BEARER_TOKEN".to_string(),
    "BETWEEN".to_string(),
    "BY".to_string(),
    "CAST".to_string(),
    "CHECK".to_string(),
    "CONNECT".to_string(),
    "CONNECTION".to_string(),
    "CONSTRAINT".to_string(),
    "CREATE".to_string(),
    "CURRENT".to_string(),
    "CURRENT_DATE".to_string(),
    "CURRENT_TIME".to_string(),
    "CURRENT_TIMESTAMP".to_string(),
    "DECLARE".to_string(),
    "DELETE".to_string(),
    "DISTINCT".to_string(),
    "DROP".to_string(),
    "ELSE".to_string(),
    "ELSEIF".to_string(),
    "EXISTS".to_string(),
    "FOLLOWING".to_string(),
    "FOR".to_string(),
    "FROM".to_string(),
    "FULL".to_string(),
    "GRANT".to_string(),
    "GROUP".to_string(),
    "GSCLUSTER".to_string(),
    "HAVING".to_string(),
    "HYBRID".to_string(),
    "ILIKE".to_string(),
    "IN".to_string(),
    "INCREMENT".to_string(),
    "INNER".to_string(),
    "INSERT".to_string(),
    "INSERT_ONLY".to_string(),
    "INTERSECT".to_string(),
    "INTO".to_string(),
    "IS".to_string(),
    "JOIN".to_string(),
    "LATERAL".to_string(),
    "LEFT".to_string(),
    "LIKE".to_string(),
    "LOCALTIME".to_string(),
    "LOCALTIMESTAMP".to_string(),
    "MATCH_CONDITION".to_string(),
    "MATCH_RECOGNIZE".to_string(),
    "MINUS".to_string(),
    "NATURAL".to_string(),
    "NOT".to_string(),
    "NULL".to_string(),
    "NULL_IF".to_string(),
    "OF".to_string(),
    "ON".to_string(),
    "OR".to_string(),
    "ORDER".to_string(),
    "QUALIFY".to_string(),
    "RAISE".to_string(),
    "REGEXP".to_string(),
    "REVOKE".to_string(),
    "RIGHT".to_string(),
    "RLIKE".to_string(),
    "ROW".to_string(),
    "ROWS".to_string(),
    "SAMPLE".to_string(),
    "SELECT".to_string(),
    "SET".to_string(),
    "SOME".to_string(),
    "START".to_string(),
    "STRICT".to_string(),
    "TABLE".to_string(),
    "TABLESAMPLE".to_string(),
    "THEN".to_string(),
    "TO".to_string(),
    "TRIGGER".to_string(),
    "TRY_CAST".to_string(),
    "UNION".to_string(),
    "UNIQUE".to_string(),
    "UNPIVOT".to_string(),
    "UPDATE".to_string(),
    "USING".to_string(),
    "VALUES".to_string(),
    "WHEN".to_string(),
    "WHENEVER".to_string(),
    "WHERE".to_string(),
    "WITH".to_string(),
]});

pub static SNOWFLAKE_LEXERS: Lazy<Vec<LexMatcher>> = Lazy::new(|| { vec![

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "inline_comment",
        r#"(--|#|//)[^\n]*"#,
        Token::comment_token_compat,
        None,
        None,
        Some(vec![String::from("--"), String::from("#"), String::from("//")]),
        None,
        None,
        None,
        None,
        None,
        |input| input.starts_with(['#','-','/']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "block_comment",
        r#"\/\*([^\*]|\*(?!\/))*\*\/"#,
        Token::comment_token_compat,
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Snowflake,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Snowflake,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        None,
        None,
        None,
        None,
        None,
        Some(extract_nested_block_comment),
        |input| input.starts_with("/"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "single_quote",
        r#"'([^'\\]|\\.|'')*'"#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |input| match input.as_bytes() {
        [b'\'', ..] => true,                     // Single quote case
        [b'R' | b'r', b'\'', ..] => true,        // r' or R'
        [b'B' | b'b', b'\'', ..] => true,        // b' or B'
        [b'R' | b'r', b'B' | b'b', b'\'', ..] => true, // rb', RB', etc.
        [b'B' | b'b', b'R' | b'r', b'\'', ..] => true, // br', Br', etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "double_quote",
        r#""(""|[^"\\]|\\.)*""#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        Some((r#""((?:[^"\\]|\\.)*)""#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\"|"""#.to_string(), r#"""#.to_string())),
        None,
        None,
        |input| match input.as_bytes() {
        [b'"', ..] => true,                     // Just a double quote
        [b'R' | b'r', b'"', ..] => true,        // r" or R"
        [b'B' | b'b', b'"', ..] => true,        // b" or B"
        [b'R' | b'r', b'B' | b'b', b'"', ..] => true, // rb", RB", etc.
        [b'B' | b'b', b'R' | b'r', b'"', ..] => true, // br", Br", etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "back_quote",
        r#"`(?:[^`\\]|\\.)*`"#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        Some((r#"`((?:[^`\\]|\\.)*)`"#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\`"#.to_string(), r#"`"#.to_string())),
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "dollar_quote",
        r#"\$(\w*)\$(.*?)\$\1\$"#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        Some((r#"\$(\w*)\$(.*?)\$\1\$"#.to_string(), RegexModeGroup::Index(2))),
        None,
        None,
        None,
        |input| input.starts_with("$"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "numeric_literal",
        r#"(?>\d+\.\d+|\d+\.(?![\.\w])|\.\d+|\d+)(\.?[eE][+-]?\d+)?((?<=\.)|(?=\b))"#,
        Token::literal_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |input| input.starts_with(['x','X','.','0','1','2','3','4','5','6','7','8','9']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "obevo_annotation",
        r#"////\s*(CHANGE|BODY|METADATA)[^\n]*"#,
        Token::comment_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "glob_operator",
        "~~~",
        Token::comparison_operator_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "parameter_assigner",
        "=>",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "right_arrow",
        "->",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "stage_path",
        r#"(?:@[^\s;)]+|'@[^']+')"#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "column_selector",
        r#"\$[0-9]+"#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "dollar_quote",
        r#"\$\$.*\$\$"#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |input| input.starts_with("$"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "dollar_literal",
        r#"[$][a-zA-Z0-9_.]*"#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "inline_dollar_sign",
        r#"[a-zA-Z_][a-zA-Z0-9_$]*\$[a-zA-Z0-9_$]*"#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "unquoted_file_path",
        r#"file://(?:[a-zA-Z]+:|/)+(?:[0-9a-zA-Z\\/_*?-]+)(?:\.[0-9a-zA-Z]+)?"#,
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "question_mark",
        "?",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "exclude_bracket_open",
        "{-",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "exclude_bracket_close",
        "-}",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "like_operator",
        r#"!?~~?\*?"#,
        Token::comparison_operator_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "casting_operator",
        "::",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "walrus_operator",
        ":=",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "equals",
        "=",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "greater_than",
        ">",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "less_than",
        "<",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "not",
        "!",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "dot",
        ".",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "comma",
        ",",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "plus",
        "+",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "minus",
        "-",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "divide",
        "/",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "percent",
        "%",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "question",
        "?",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "ampersand",
        "&",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "vertical_bar",
        "|",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "caret",
        "^",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "star",
        "*",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "start_bracket",
        "(",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "end_bracket",
        ")",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "start_square_bracket",
        "[",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "end_square_bracket",
        "]",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "start_curly_bracket",
        "{",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "end_curly_bracket",
        "}",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "colon",
        ":",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Snowflake,
        "semicolon",
        ";",
        Token::code_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Snowflake,
        "word",
        r#"[0-9a-zA-Z_]+"#,
        Token::word_token_compat,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),
]});
