/* This is a generated file! */
use once_cell::sync::Lazy;
use uuid::Uuid;
use crate::matcher::{LexMatcher, extract_nested_block_comment};
use crate::token::Token;
use crate::regex::RegexModeGroup;
use crate::dialect::Dialect;

pub static BIGQUERY_KEYWORDS: Lazy<Vec<String>> = Lazy::new(|| { vec![
    "AGGREGATE".to_string(),
    "ALL".to_string(),
    "AND".to_string(),
    "ANY".to_string(),
    "ARRAY".to_string(),
    "AS".to_string(),
    "ASC".to_string(),
    "ASSERT_ROWS_MODIFIED".to_string(),
    "AT".to_string(),
    "BETWEEN".to_string(),
    "BY".to_string(),
    "CASE".to_string(),
    "CAST".to_string(),
    "CLONE".to_string(),
    "COLLATE".to_string(),
    "CONTAINS".to_string(),
    "CORRESPONDING".to_string(),
    "CREATE".to_string(),
    "CROSS".to_string(),
    "CUBE".to_string(),
    "CURRENT".to_string(),
    "DEFAULT".to_string(),
    "DEFINE".to_string(),
    "DESC".to_string(),
    "DISTINCT".to_string(),
    "ELSE".to_string(),
    "END".to_string(),
    "ENUM".to_string(),
    "ESCAPE".to_string(),
    "EXCEPT".to_string(),
    "EXCLUDE".to_string(),
    "EXISTS".to_string(),
    "EXTEND".to_string(),
    "FALSE".to_string(),
    "FETCH".to_string(),
    "FOLLOWING".to_string(),
    "FOR".to_string(),
    "FROM".to_string(),
    "FULL".to_string(),
    "GROUP".to_string(),
    "GROUPING".to_string(),
    "GROUPS".to_string(),
    "HASH".to_string(),
    "HAVING".to_string(),
    "IF".to_string(),
    "IGNORE".to_string(),
    "IN".to_string(),
    "INCLUDE".to_string(),
    "INNER".to_string(),
    "INTERSECT".to_string(),
    "INTERVAL".to_string(),
    "INTO".to_string(),
    "IS".to_string(),
    "JOIN".to_string(),
    "LATERAL".to_string(),
    "LEFT".to_string(),
    "LIKE".to_string(),
    "LIMIT".to_string(),
    "LOOKUP".to_string(),
    "MERGE".to_string(),
    "NEW".to_string(),
    "NO".to_string(),
    "NOT".to_string(),
    "NULL".to_string(),
    "NULLS".to_string(),
    "OF".to_string(),
    "ON".to_string(),
    "OR".to_string(),
    "ORDER".to_string(),
    "OUTER".to_string(),
    "OVER".to_string(),
    "PARTITION".to_string(),
    "PIVOT".to_string(),
    "PRECEDING".to_string(),
    "PRIMARY".to_string(),
    "PROTO".to_string(),
    "RANGE".to_string(),
    "RECURSIVE".to_string(),
    "RESPECT".to_string(),
    "RIGHT".to_string(),
    "ROLLUP".to_string(),
    "ROWS".to_string(),
    "SELECT".to_string(),
    "SET".to_string(),
    "SOME".to_string(),
    "STRUCT".to_string(),
    "TABLESAMPLE".to_string(),
    "THEN".to_string(),
    "TO".to_string(),
    "TREAT".to_string(),
    "TRUE".to_string(),
    "UNBOUNDED".to_string(),
    "UNION".to_string(),
    "UNNEST".to_string(),
    "UNPIVOT".to_string(),
    "USING".to_string(),
    "WHEN".to_string(),
    "WHERE".to_string(),
    "WINDOW".to_string(),
    "WITH".to_string(),
    "WITHIN".to_string(),
]});

pub static BIGQUERY_LEXERS: Lazy<Vec<LexMatcher>> = Lazy::new(|| { vec![

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "inline_comment",
        r#"(--|#)[^\n]*"#,
        Token::comment_token,
        None,
        None,
        Some(vec![String::from("--"), String::from("#")]),
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |input| input.starts_with(['#','-','/']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "block_comment",
        r#"\/\*([^\*]|\*(?!\/))*\*\/"#,
        Token::comment_token,
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Bigquery,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Bigquery,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        Some(extract_nested_block_comment),
        |input| input.starts_with("/"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "single_quote",
        r#"([rR]?[bB]?|[bB]?[rR]?)?('''((?<!\\)(\\{2})*\\'|'{,2}(?!')|[^'])*(?<!\\)(\\{2})*'''|'((?<!\\)(\\{2})*\\'|[^'])*(?<!\\)(\\{2})*')"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"(?:[rR]?[bB]?|[bB]?[rR]?)?(?:'''(?<value>(?:(?<!\\)(?:\\{2})*\\'|'{,2}(?!')|[^'])*(?<!\\)(?:\\{2})*)'''|'(?<value>(?:(?<!\\)(?:\\{2})*\\'|[^'])*(?<!\\)(?:\\{2})*)')"#.to_string(), RegexModeGroup::Name("value".to_string()))),
        Some((r#"\\([\\`\"'?])"#.to_string(), r#"\1"#.to_string())),
        None,
        None,
        |input| match input.as_bytes() {
        [b'\'', ..] => true,                     // Single quote case
        [b'R' | b'r', b'\'', ..] => true,        // r' or R'
        [b'B' | b'b', b'\'', ..] => true,        // b' or B'
        [b'R' | b'r', b'B' | b'b', b'\'', ..] => true, // rb', RB', etc.
        [b'B' | b'b', b'R' | b'r', b'\'', ..] => true, // br', Br', etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "double_quote",
        r#"([rR]?[bB]?|[bB]?[rR]?)?(\"\"\"((?<!\\)(\\{2})*\\\"|\"{,2}(?!\")|[^\"])*(?<!\\)(\\{2})*\"\"\"|"((?<!\\)(\\{2})*\\"|[^"])*(?<!\\)(\\{2})*")"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"([rR]?[bB]?|[bB]?[rR]?)?(\"\"\"(?<value>((?<!\\)(\\{2})*\\\"|\"{,2}(?!\")|[^\"])*(?<!\\)(\\{2})*)\"\"\"|"(?<value>((?<!\\)(\\{2})*\\"|[^"])*(?<!\\)(\\{2})*)")"#.to_string(), RegexModeGroup::Name("value".to_string()))),
        Some((r#"\\([\\`\"'?])"#.to_string(), r#"\1"#.to_string())),
        None,
        None,
        |input| match input.as_bytes() {
        [b'"', ..] => true,                     // Just a double quote
        [b'R' | b'r', b'"', ..] => true,        // r" or R"
        [b'B' | b'b', b'"', ..] => true,        // b" or B"
        [b'R' | b'r', b'B' | b'b', b'"', ..] => true, // rb", RB", etc.
        [b'B' | b'b', b'R' | b'r', b'"', ..] => true, // br", Br", etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "back_quote",
        r#"`(?:[^`\\]|\\.)*`"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"`((?:[^`\\]|\\.)*)`"#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\`"#.to_string(), r#"`"#.to_string())),
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "dollar_quote",
        r#"\$(\w*)\$(.*?)\$\1\$"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"\$(\w*)\$(.*?)\$\1\$"#.to_string(), RegexModeGroup::Index(2))),
        None,
        None,
        None,
        |input| input.starts_with("$"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "numeric_literal",
        r#"(?>\d+\.\d+|\d+\.(?![\.\w])|\.\d+|\d+)(\.?[eE][+-]?\d+)?((?<=\.)|(?=\b))"#,
        Token::literal_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |input| input.starts_with(['x','X','.','0','1','2','3','4','5','6','7','8','9']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "obevo_annotation",
        r#"////\s*(CHANGE|BODY|METADATA)[^\n]*"#,
        Token::comment_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "glob_operator",
        "~~~",
        Token::comparison_operator_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "like_operator",
        r#"!?~~?\*?"#,
        Token::comparison_operator_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "casting_operator",
        "::",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "right_arrow",
        "=>",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "question_mark",
        "?",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "at_sign_literal",
        r#"@[a-zA-Z_][\w]*"#,
        Token::literal_token,
        None,
        None,
        None,
        Some(vec![String::from("@")]),
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "double_at_sign_literal",
        r#"@@[a-zA-Z_][\w\.]*"#,
        Token::literal_token,
        None,
        None,
        None,
        Some(vec![String::from("@@")]),
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "pipe_operator",
        "|>",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "equals",
        "=",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "greater_than",
        ">",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "less_than",
        "<",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "not",
        "!",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "dot",
        ".",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "comma",
        ",",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "plus",
        "+",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "minus",
        "-",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "divide",
        "/",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "percent",
        "%",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "question",
        "?",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "ampersand",
        "&",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "vertical_bar",
        "|",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "caret",
        "^",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "star",
        "*",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "start_bracket",
        "(",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "end_bracket",
        ")",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "start_square_bracket",
        "[",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "end_square_bracket",
        "]",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "start_curly_bracket",
        "{",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "end_curly_bracket",
        "}",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "colon",
        ":",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Bigquery,
        "semicolon",
        ";",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Bigquery,
        "word",
        r#"[0-9a-zA-Z_]+"#,
        Token::word_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),
]});
