/* This is a generated file! */
/* Generated by `utils/build_dialect.py` via `utils/rustify.py` */
/* This process can be run via tox: `tox -e generate-rs` */

#[allow(clippy::needless_raw_string_hashes)]
pub mod matcher;
pub mod parser;
