/* This is a generated file! */
use once_cell::sync::Lazy;
use uuid::Uuid;
use crate::matcher::{LexMatcher, extract_nested_block_comment};
use crate::token::Token;
use crate::regex::RegexModeGroup;
use crate::dialect::Dialect;

pub static DATABRICKS_LEXERS: Lazy<Vec<LexMatcher>> = Lazy::new(|| { vec![

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "notebook_start",
        r#"-- Databricks notebook source(\r?\n){1}"#,
        Token::comment_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "magic_single_line",
        r#"(-- MAGIC %)([^\n]{2,})( [^%]{1})([^\n]*)"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "magic_line",
        r#"(-- MAGIC)( [^%]{1})([^\n]*)"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "magic_start",
        r#"(-- MAGIC %)([^\n]{2,})(\r?\n)"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "inline_comment",
        r#"(--)[^\n]*"#,
        Token::comment_token,
        None,
        None,
        Some(vec![String::from("-"), String::from("-")]),
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |input| input.starts_with(['#','-','/']),
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "start_hint",
        "/*+",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "block_comment",
        r#"\/\*([^\*]|\*(?!\/))*\*\/"#,
        Token::comment_token,
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Databricks,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Databricks,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        Some(extract_nested_block_comment),
        |input| input.starts_with("/"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "raw_single_quote",
        r#"[rR]'([^'\\]|\\.)*'"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "raw_double_quote",
        r#"[rR]"([^"\\]|\\.)*""#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "bytes_single_quote",
        r#"X'([^'\\]|\\.)*'"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "bytes_double_quote",
        r#"X"([^"\\]|\\.)*""#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "end_hint",
        "*/",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "single_quote",
        r#"'([^'\\]|\\.|'')*'"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"'((?:[^'\\]|\\.|'')*)'"#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\'|''"#.to_string(), r#"'"#.to_string())),
        None,
        None,
        |input| match input.as_bytes() {
        [b'\'', ..] => true,                     // Single quote case
        [b'R' | b'r', b'\'', ..] => true,        // r' or R'
        [b'B' | b'b', b'\'', ..] => true,        // b' or B'
        [b'R' | b'r', b'B' | b'b', b'\'', ..] => true, // rb', RB', etc.
        [b'B' | b'b', b'R' | b'r', b'\'', ..] => true, // br', Br', etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "double_quote",
        r#""(""|[^"\\]|\\.)*""#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#""((?:[^"\\]|\\.)*)""#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\"|"""#.to_string(), r#"""#.to_string())),
        None,
        None,
        |input| match input.as_bytes() {
        [b'"', ..] => true,                     // Just a double quote
        [b'R' | b'r', b'"', ..] => true,        // r" or R"
        [b'B' | b'b', b'"', ..] => true,        // b" or B"
        [b'R' | b'r', b'B' | b'b', b'"', ..] => true, // rb", RB", etc.
        [b'B' | b'b', b'R' | b'r', b'"', ..] => true, // br", Br", etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "back_quote",
        r#"`([^`]|``)*`"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"`((?:[^`]|``)*)`"#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"``"#.to_string(), r#"`"#.to_string())),
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "dollar_quote",
        r#"\$(\w*)\$(.*?)\$\1\$"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"\$(\w*)\$(.*?)\$\1\$"#.to_string(), RegexModeGroup::Index(2))),
        None,
        None,
        None,
        |input| input.starts_with("$"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "numeric_literal",
        r#"(?>(?>\d+\.\d+|\d+\.|\.\d+)([eE][+-]?\d+)?([dDfF]|BD|bd)?|\d+[eE][+-]?\d+([dDfF]|BD|bd)?|\d+([dDfFlLsSyY]|BD|bd)?)((?<=\.)|(?=\b))"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |input| input.starts_with(['x','X','.','0','1','2','3','4','5','6','7','8','9']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "obevo_annotation",
        r#"////\s*(CHANGE|BODY|METADATA)[^\n]*"#,
        Token::comment_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "glob_operator",
        "~~~",
        Token::comparison_operator_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "right_arrow",
        "->",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "like_operator",
        r#"!?~~?\*?"#,
        Token::comparison_operator_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "file_literal",
        r#"[a-zA-Z0-9]+:([a-zA-Z0-9\-_\.]*(\/|\\)){2,}((([a-zA-Z0-9\-_\.]*(:|\?|=|&)[a-zA-Z0-9\-_\.]*)+)|([a-zA-Z0-9\-_\.]*\.[a-z]+))"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "command",
        r#"(\r?\n){2}-- COMMAND ----------(\r?\n)"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "casting_operator",
        "::",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "right_arrow",
        "=>",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "equals",
        r#"==|<=>|="#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "greater_than",
        ">",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "less_than",
        "<",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "not",
        "!",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "dot",
        ".",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "comma",
        ",",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "plus",
        "+",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "minus",
        "-",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "divide",
        "/",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "percent",
        "%",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "question",
        "?",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "ampersand",
        "&",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "vertical_bar",
        "|",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "caret",
        "^",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "star",
        "*",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "start_bracket",
        "(",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "end_bracket",
        ")",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "start_square_bracket",
        "[",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "end_square_bracket",
        "]",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "start_curly_bracket",
        "{",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "end_curly_bracket",
        "}",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "colon",
        ":",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Databricks,
        "semicolon",
        ";",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "at_sign_literal",
        r#"@\w*"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Databricks,
        "word",
        r#"[0-9a-zA-Z_]+"#,
        Token::word_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),
]});

pub static DATABRICKS_KEYWORDS: Lazy<Vec<String>> = Lazy::new(|| { vec![
    "INTERSECT".to_string(),
    "CROSS".to_string(),
    "LATERAL".to_string(),
    "EXCEPT".to_string(),
    "NATURAL".to_string(),
    "INNER".to_string(),
    "USING".to_string(),
    "MINUS".to_string(),
    "ON".to_string(),
    "ANTI".to_string(),
    "LEFT".to_string(),
    "RIGHT".to_string(),
    "FULL".to_string(),
    "UNION".to_string(),
    "JOIN".to_string(),
    "SEMI".to_string(),
]});
