"""For autogenerating rust dialects."""

import sys


def generate_use():
    """Generates the `use` statements."""
    print("#[allow(clippy::needless_raw_string_hashes)]")
    print("pub mod matcher;")
    print("pub mod parser;")


if __name__ == "__main__":
    sys.stdout.reconfigure(newline="\n")  # Force LF line endings for consistency
    print("/* This is a generated file! */")
    print("/* Generated by `utils/build_dialect.py` via `utils/rustify.py` */")
    print("/* This process can be run via tox: `tox -e generate-rs` */")
    print()
    generate_use()
