/* This is a generated file! */
/* Generated by `utils/build_parsers.py` via `utils/rustify.py` */
/* This process can be run via tox: `tox -e generate-rs` */
#![cfg_attr(rustfmt, rustfmt_skip)]

use sqlfluffrs_types::{ RootGrammar, GrammarId };

pub fn get_redshift_segment_grammar(name: &str) -> Option<RootGrammar> {
    // Not generated yet for this dialect
    unimplemented!()
}

pub fn get_redshift_segment_type(name: &str) -> Option<&'static str> {
    unimplemented!()
}

pub fn get_redshift_root_grammar_arc() -> RootGrammar {
    unimplemented!()
}

pub fn get_redshift_root_grammar() -> RootGrammar {
    unimplemented!()
}

