/* This is a generated file! */
use once_cell::sync::Lazy;
use uuid::Uuid;
use crate::matcher::{LexMatcher, extract_nested_block_comment};
use crate::token::Token;
use crate::regex::RegexModeGroup;
use crate::dialect::Dialect;

pub static ATHENA_LEXERS: Lazy<Vec<LexMatcher>> = Lazy::new(|| { vec![

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "inline_comment",
        r#"(--|#)[^\n]*"#,
        Token::comment_token,
        None,
        None,
        Some(vec![String::from("--"), String::from("#")]),
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |input| input.starts_with(['#','-','/']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "block_comment",
        r#"\/\*([^\*]|\*(?!\/))*\*\/"#,
        Token::comment_token,
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Athena,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Athena,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        Some(extract_nested_block_comment),
        |input| input.starts_with("/"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "single_quote",
        r#"'([^'\\]|\\.|'')*'"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"'((?:[^'\\]|\\.|'')*)'"#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\'|''"#.to_string(), r#"'"#.to_string())),
        None,
        None,
        |input| match input.as_bytes() {
        [b'\'', ..] => true,                     // Single quote case
        [b'R' | b'r', b'\'', ..] => true,        // r' or R'
        [b'B' | b'b', b'\'', ..] => true,        // b' or B'
        [b'R' | b'r', b'B' | b'b', b'\'', ..] => true, // rb', RB', etc.
        [b'B' | b'b', b'R' | b'r', b'\'', ..] => true, // br', Br', etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "double_quote",
        r#""(""|[^"\\]|\\.)*""#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#""((?:[^"\\]|\\.)*)""#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\"|"""#.to_string(), r#"""#.to_string())),
        None,
        None,
        |input| match input.as_bytes() {
        [b'"', ..] => true,                     // Just a double quote
        [b'R' | b'r', b'"', ..] => true,        // r" or R"
        [b'B' | b'b', b'"', ..] => true,        // b" or B"
        [b'R' | b'r', b'B' | b'b', b'"', ..] => true, // rb", RB", etc.
        [b'B' | b'b', b'R' | b'r', b'"', ..] => true, // br", Br", etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "back_quote",
        r#"`(?:[^`\\]|\\.)*`"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"`((?:[^`\\]|\\.)*)`"#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\`"#.to_string(), r#"`"#.to_string())),
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "dollar_quote",
        r#"\$(\w*)\$(.*?)\$\1\$"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        Some((r#"\$(\w*)\$(.*?)\$\1\$"#.to_string(), RegexModeGroup::Index(2))),
        None,
        None,
        None,
        |input| input.starts_with("$"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "numeric_literal",
        r#"(?>\d+\.\d+|\d+\.(?![\.\w])|\.\d+|\d+)(\.?[eE][+-]?\d+)?((?<=\.)|(?=\b))"#,
        Token::literal_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |input| input.starts_with(['x','X','.','0','1','2','3','4','5','6','7','8','9']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "obevo_annotation",
        r#"////\s*(CHANGE|BODY|METADATA)[^\n]*"#,
        Token::comment_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "glob_operator",
        "~~~",
        Token::comparison_operator_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "right_arrow",
        "->",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "like_operator",
        r#"!?~~?\*?"#,
        Token::comparison_operator_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "casting_operator",
        "::",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "equals",
        "=",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "greater_than",
        ">",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "less_than",
        "<",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "not",
        "!",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "dot",
        ".",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "comma",
        ",",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "plus",
        "+",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "minus",
        "-",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "divide",
        "/",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "percent",
        "%",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "question",
        "?",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "ampersand",
        "&",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "vertical_bar",
        "|",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "caret",
        "^",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "star",
        "*",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "start_bracket",
        "(",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "end_bracket",
        ")",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "start_square_bracket",
        "[",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "end_square_bracket",
        "]",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "start_curly_bracket",
        "{",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "end_curly_bracket",
        "}",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "colon",
        ":",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Athena,
        "semicolon",
        ";",
        Token::code_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Athena,
        "word",
        r#"[0-9a-zA-Z_]+"#,
        Token::word_token,
        None,
        None,
        None,
        None,
        Uuid::new_v4().to_string(),
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),
]});

pub static ATHENA_KEYWORDS: Lazy<Vec<String>> = Lazy::new(|| { vec![
    "EXTERNAL".to_string(),
    "ROLLUP".to_string(),
    "USING".to_string(),
    "SYNC".to_string(),
    "PRIMARY".to_string(),
    "WHERE".to_string(),
    "DELETE".to_string(),
    "EXISTS".to_string(),
    "READS".to_string(),
    "IGNORE".to_string(),
    "ALL".to_string(),
    "TRANSFORM".to_string(),
    "COLUMN".to_string(),
    "OUT".to_string(),
    "OF".to_string(),
    "FULL".to_string(),
    "PARTIALSCAN".to_string(),
    "REVOKE".to_string(),
    "UPDATE".to_string(),
    "INT".to_string(),
    "GROUPING".to_string(),
    "NUMERIC".to_string(),
    "REFERENCES".to_string(),
    "EXCHANGE".to_string(),
    "FLOOR".to_string(),
    "PRECEDING".to_string(),
    "REGEXP".to_string(),
    "TRUNCATE".to_string(),
    "IF".to_string(),
    "AND".to_string(),
    "LEFT".to_string(),
    "VARCHAR".to_string(),
    "CROSS".to_string(),
    "NOT".to_string(),
    "BINARY".to_string(),
    "PREPARE".to_string(),
    "BY".to_string(),
    "TABLE".to_string(),
    "INTEGER".to_string(),
    "BOTH".to_string(),
    "ORDER".to_string(),
    "FROM".to_string(),
    "MACRO".to_string(),
    "FOR".to_string(),
    "UNBOUNDED".to_string(),
    "TO".to_string(),
    "CONSTRAINT".to_string(),
    "UNION".to_string(),
    "ON".to_string(),
    "IMPORT".to_string(),
    "TRIGGER".to_string(),
    "LESS".to_string(),
    "RLIKE".to_string(),
    "PERCENT".to_string(),
    "GROUP".to_string(),
    "INNER".to_string(),
    "RIGHT".to_string(),
    "SET".to_string(),
    "JOIN".to_string(),
    "CURRENT".to_string(),
    "VALUES".to_string(),
    "OUTER".to_string(),
    "CURSOR".to_string(),
    "RANGE".to_string(),
    "START".to_string(),
    "FALSE".to_string(),
    "NONE".to_string(),
    "ROLLBACK".to_string(),
    "DECIMAL".to_string(),
    "INTO".to_string(),
    "INTERSECT".to_string(),
    "REDUCE".to_string(),
    "LIKE".to_string(),
    "CREATE".to_string(),
    "MORE".to_string(),
    "PARTITION".to_string(),
    "LATERAL".to_string(),
    "AS".to_string(),
    "INTERVAL".to_string(),
    "EXTENDED".to_string(),
    "BOOLEAN".to_string(),
    "WITH".to_string(),
    "FLOAT".to_string(),
    "ALTER".to_string(),
    "PRECISION".to_string(),
    "CUBE".to_string(),
    "BIGINT".to_string(),
    "CAST".to_string(),
    "DISTINCT".to_string(),
    "IN".to_string(),
    "CURRENT_TIMESTAMP".to_string(),
    "BETWEEN".to_string(),
    "LOCAL".to_string(),
    "EXTRACT".to_string(),
    "PRESERVE".to_string(),
    "THEN".to_string(),
    "FOREIGN".to_string(),
    "INSERT".to_string(),
    "ONLY".to_string(),
    "AUTHORIZATION".to_string(),
    "CASE".to_string(),
    "ARRAY".to_string(),
    "PROCEDURE".to_string(),
    "FETCH".to_string(),
    "UNIQUEJOIN".to_string(),
    "OVER".to_string(),
    "WHEN".to_string(),
    "COMMIT".to_string(),
    "RESPECT".to_string(),
    "NATURAL".to_string(),
    "END".to_string(),
    "SELECT".to_string(),
    "NULL".to_string(),
    "GRANT".to_string(),
    "DATABASE".to_string(),
    "IS".to_string(),
    "CONF".to_string(),
    "CHAR".to_string(),
    "OR".to_string(),
    "ELSE".to_string(),
    "SMALLINT".to_string(),
    "FOLLOWING".to_string(),
    "DOUBLE".to_string(),
    "UTC_TMESTAMP".to_string(),
    "MAP".to_string(),
    "DROP".to_string(),
    "TABLESAMPLE".to_string(),
    "CACHE".to_string(),
    "ROWS".to_string(),
    "HAVING".to_string(),
    "FUNCTION".to_string(),
    "CURRENT_DATE".to_string(),
    "TRUE".to_string(),
    "DESCRIBE".to_string(),
]});
