/* This is a generated file! */
use once_cell::sync::Lazy;
use uuid::Uuid;
use crate::matcher::{LexMatcher, extract_nested_block_comment};
use crate::token::Token;
use crate::regex::RegexModeGroup;
use crate::dialect::Dialect;

pub static TSQL_KEYWORDS: Lazy<Vec<String>> = Lazy::new(|| { vec![
    "ADD".to_string(),
    "ALL".to_string(),
    "ALTER".to_string(),
    "AND".to_string(),
    "ANY".to_string(),
    "APPEND".to_string(),
    "AS".to_string(),
    "ASC".to_string(),
    "AUTHORIZATION".to_string(),
    "BACKUP".to_string(),
    "BATCHSIZE".to_string(),
    "BEGIN".to_string(),
    "BETWEEN".to_string(),
    "BREAK".to_string(),
    "BROWSE".to_string(),
    "BULK".to_string(),
    "BY".to_string(),
    "CASCADE".to_string(),
    "CASE".to_string(),
    "CHECK".to_string(),
    "CHECKPOINT".to_string(),
    "CHECK_CONSTRAINTS".to_string(),
    "CLOSE".to_string(),
    "CLUSTERED".to_string(),
    "COALESCE".to_string(),
    "COLLATE".to_string(),
    "COLUMN".to_string(),
    "COMMIT".to_string(),
    "COMPUTE".to_string(),
    "CONSTRAINT".to_string(),
    "CONTAINS".to_string(),
    "CONTAINSTABLE".to_string(),
    "CONTINUE".to_string(),
    "CONVERT".to_string(),
    "CREATE".to_string(),
    "CROSS".to_string(),
    "CURRENT".to_string(),
    "CURRENT_CATALOG".to_string(),
    "CURRENT_DATE".to_string(),
    "CURRENT_DEFAULT_TRANSFORM_GROUP".to_string(),
    "CURRENT_PATH".to_string(),
    "CURRENT_ROLE".to_string(),
    "CURRENT_SCHEMA".to_string(),
    "CURRENT_TIME".to_string(),
    "CURRENT_TIMESTAMP".to_string(),
    "CURRENT_TRANSFORM_GROUP_FOR_TYPE".to_string(),
    "CURRENT_USER".to_string(),
    "CURSOR".to_string(),
    "DATABASE".to_string(),
    "DBCC".to_string(),
    "DEALLOCATE".to_string(),
    "DECLARE".to_string(),
    "DECRYPTION".to_string(),
    "DEFAULT".to_string(),
    "DELETE".to_string(),
    "DENY".to_string(),
    "DESC".to_string(),
    "DISTINCT".to_string(),
    "DISTRIBUTED".to_string(),
    "DOUBLE".to_string(),
    "DROP".to_string(),
    "DYNAMIC".to_string(),
    "ELSE".to_string(),
    "END".to_string(),
    "ERRLVL".to_string(),
    "ESCAPE".to_string(),
    "EXCEPT".to_string(),
    "EXEC".to_string(),
    "EXECUTE".to_string(),
    "EXISTS".to_string(),
    "EXIT".to_string(),
    "EXTERNAL".to_string(),
    "FAST_FORWARD".to_string(),
    "FETCH".to_string(),
    "FILE".to_string(),
    "FILLFACTOR".to_string(),
    "FOR".to_string(),
    "FOREIGN".to_string(),
    "FORWARD_ONLY".to_string(),
    "FREETEXT".to_string(),
    "FREETEXTTABLE".to_string(),
    "FROM".to_string(),
    "FULL".to_string(),
    "FULLSCAN".to_string(),
    "FUNCTION".to_string(),
    "GLOBAL".to_string(),
    "GO".to_string(),
    "GOTO".to_string(),
    "GRANT".to_string(),
    "GROUP".to_string(),
    "HAVING".to_string(),
    "HOLDLOCK".to_string(),
    "IDENTITY".to_string(),
    "IDENTITYCOL".to_string(),
    "IDENTITY_INSERT".to_string(),
    "IF".to_string(),
    "IN".to_string(),
    "INDEX".to_string(),
    "INNER".to_string(),
    "INSERT".to_string(),
    "INTERSECT".to_string(),
    "INTO".to_string(),
    "IS".to_string(),
    "JOIN".to_string(),
    "KEY".to_string(),
    "KEYSET".to_string(),
    "KILL".to_string(),
    "LEFT".to_string(),
    "LIKE".to_string(),
    "LINENO".to_string(),
    "LIST".to_string(),
    "LOCAL".to_string(),
    "MERGE".to_string(),
    "NATIONAL".to_string(),
    "NATIVE_COMPILATION".to_string(),
    "NOCHECK".to_string(),
    "NONCLUSTERED".to_string(),
    "NOT".to_string(),
    "NULL".to_string(),
    "NULLIF".to_string(),
    "OF".to_string(),
    "OFF".to_string(),
    "OFFSETS".to_string(),
    "ON".to_string(),
    "OPEN".to_string(),
    "OPENDATASOURCE".to_string(),
    "OPENQUERY".to_string(),
    "OPENROWSET".to_string(),
    "OPENXML".to_string(),
    "OPTIMISTIC".to_string(),
    "OPTION".to_string(),
    "OR".to_string(),
    "ORDER".to_string(),
    "OUTER".to_string(),
    "OVER".to_string(),
    "OVERLAY".to_string(),
    "PERCENT".to_string(),
    "PIVOT".to_string(),
    "PLAN".to_string(),
    "PRIMARY".to_string(),
    "PRINT".to_string(),
    "PROC".to_string(),
    "PROCEDURE".to_string(),
    "PUBLIC".to_string(),
    "RAISERROR".to_string(),
    "READ".to_string(),
    "READTEXT".to_string(),
    "READ_ONLY".to_string(),
    "RECONFIGURE".to_string(),
    "REFERENCES".to_string(),
    "REPLICATION".to_string(),
    "RESAMPLE".to_string(),
    "RESTORE".to_string(),
    "RESTRICT".to_string(),
    "RETURN".to_string(),
    "REVERT".to_string(),
    "REVOKE".to_string(),
    "RIGHT".to_string(),
    "ROLLBACK".to_string(),
    "ROWCOUNT".to_string(),
    "ROWGUIDCOL".to_string(),
    "RULE".to_string(),
    "SAVE".to_string(),
    "SCHEMA".to_string(),
    "SCROLL".to_string(),
    "SCROLL_LOCKS".to_string(),
    "SELECT".to_string(),
    "SEMANTICKEYPHRASETABLE".to_string(),
    "SEMANTICSIMILARITYDETAILSTABLE".to_string(),
    "SEMANTICSIMILARITYTABLE".to_string(),
    "SESSION_USER".to_string(),
    "SET".to_string(),
    "SETUSER".to_string(),
    "SHUTDOWN".to_string(),
    "SOME".to_string(),
    "STATIC".to_string(),
    "STATISTICS".to_string(),
    "SYMMETRIC".to_string(),
    "SYSTEM_USER".to_string(),
    "TABLE".to_string(),
    "TABLESAMPLE".to_string(),
    "TEXTSIZE".to_string(),
    "THEN".to_string(),
    "THROW".to_string(),
    "TO".to_string(),
    "TOP".to_string(),
    "TRAN".to_string(),
    "TRANSACTION".to_string(),
    "TRIGGER".to_string(),
    "TRUNCATE".to_string(),
    "TRY_CONVERT".to_string(),
    "TSEQUAL".to_string(),
    "TYPE_WARNING".to_string(),
    "UNION".to_string(),
    "UNIQUE".to_string(),
    "UNPIVOT".to_string(),
    "UPDATE".to_string(),
    "UPDATETEXT".to_string(),
    "USE".to_string(),
    "USER".to_string(),
    "VALUES".to_string(),
    "VARYING".to_string(),
    "VIEW".to_string(),
    "WAITFOR".to_string(),
    "WHEN".to_string(),
    "WHERE".to_string(),
    "WHILE".to_string(),
    "WINDOW".to_string(),
    "WITH".to_string(),
    "WRITETEXT".to_string(),
]});

pub static TSQL_LEXERS: Lazy<Vec<LexMatcher>> = Lazy::new(|| { vec![

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "inline_comment",
        r#"(--)[^\n]*"#,
        Token::comment_token,
        None,
        None,
        Some(vec![String::from("-"), String::from("-")]),
        None,
        None,
        None,
        None,
        None,
        |input| input.starts_with(['#','-','/']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "block_comment",
        r#"/\*(?>[^*/]+|\*(?!\/)|/[^*])*(?>(?R)(?>[^*/]+|\*(?!\/)|/[^*])*)*\*/"#,
        Token::comment_token,
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Tsql,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        Some(Box::new(
    LexMatcher::regex_subdivider(
        Dialect::Tsql,
        "whitespace",
        r#"[^\S\r\n]+"#,
        Token::whitespace_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ))),
        None,
        None,
        None,
        None,
        None,
        Some(extract_nested_block_comment),
        |input| input.starts_with("/"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "single_quote",
        r#"'([^']|'')*'"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |input| match input.as_bytes() {
        [b'\'', ..] => true,                     // Single quote case
        [b'R' | b'r', b'\'', ..] => true,        // r' or R'
        [b'B' | b'b', b'\'', ..] => true,        // b' or B'
        [b'R' | b'r', b'B' | b'b', b'\'', ..] => true, // rb', RB', etc.
        [b'B' | b'b', b'R' | b'r', b'\'', ..] => true, // br', Br', etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "double_quote",
        r#""(""|[^"\\]|\\.)*""#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Some((r#""((?:[^"\\]|\\.)*)""#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\"|"""#.to_string(), r#"""#.to_string())),
        None,
        None,
        |input| match input.as_bytes() {
        [b'"', ..] => true,                     // Just a double quote
        [b'R' | b'r', b'"', ..] => true,        // r" or R"
        [b'B' | b'b', b'"', ..] => true,        // b" or B"
        [b'R' | b'r', b'B' | b'b', b'"', ..] => true, // rb", RB", etc.
        [b'B' | b'b', b'R' | b'r', b'"', ..] => true, // br", Br", etc.
        _ => false,
    },
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "atsign",
        r#"[@][a-zA-Z0-9_]+"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "var_prefix",
        r#"[$][a-zA-Z0-9_]+"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "square_quote",
        r#"\[([^\[\]]*)*\]"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Some((r#"\[([^\[\]]*)\]"#.to_string(), RegexModeGroup::Index(1))),
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "single_quote_with_n",
        r#"N'([^']|'')*'"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Some((r#"N'((?:[^']|'')*)'"#.to_string(), RegexModeGroup::Index(1))),
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "hash_prefix",
        r#"[#][#]?[a-zA-Z0-9_]+"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "unquoted_relative_sql_file_path",
        r#"[.\w\\/#-]+\.[sS][qQ][lL]\b"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "back_quote",
        r#"`(?:[^`\\]|\\.)*`"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Some((r#"`((?:[^`\\]|\\.)*)`"#.to_string(), RegexModeGroup::Index(1))),
        Some((r#"\\`"#.to_string(), r#"`"#.to_string())),
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "dollar_quote",
        r#"\$(\w*)\$(.*?)\$\1\$"#,
        Token::code_token,
        None,
        None,
        None,
        None,
        Some((r#"\$(\w*)\$(.*?)\$\1\$"#.to_string(), RegexModeGroup::Index(2))),
        None,
        None,
        None,
        |input| input.starts_with("$"),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "numeric_literal",
        r#"(?>\d+\.\d+|\d+\.(?![\.\w])|\.\d+|\d+)(\.?[eE][+-]?\d+)?((?<=\.)|(?=\b))"#,
        Token::literal_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |input| input.starts_with(['x','X','.','0','1','2','3','4','5','6','7','8','9']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "obevo_annotation",
        r#"////\s*(CHANGE|BODY|METADATA)[^\n]*"#,
        Token::comment_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "glob_operator",
        "~~~",
        Token::comparison_operator_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "like_operator",
        r#"!?~~?\*?"#,
        Token::comparison_operator_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "newline",
        r#"\r\n|\n"#,
        Token::newline_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "casting_operator",
        "::",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "equals",
        "=",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "greater_than",
        ">",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "less_than",
        "<",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "not",
        "!",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "dot",
        ".",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "comma",
        ",",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "plus",
        "+",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "minus",
        "-",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "divide",
        "/",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "percent",
        "%",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "question",
        "?",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "ampersand",
        "&",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "vertical_bar",
        "|",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "caret",
        "^",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "star",
        "*",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "start_bracket",
        "(",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "end_bracket",
        ")",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "start_square_bracket",
        "[",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "end_square_bracket",
        "]",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "start_curly_bracket",
        "{",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "end_curly_bracket",
        "}",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "colon",
        ":",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::string_lexer(
        Dialect::Tsql,
        "semicolon",
        ";",
        Token::code_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "numeric_literal",
        r#"([xX]'([\da-fA-F][\da-fA-F])+'|0[xX][\da-fA-F]*)"#,
        Token::literal_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |input| input.starts_with(['x','X','.','0','1','2','3','4','5','6','7','8','9']),
        None,
    ),

    LexMatcher::regex_lexer(
        Dialect::Tsql,
        "word",
        r#"[0-9a-zA-Z_#@\p{L}]+"#,
        Token::word_token,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        |_| true,
        None,
    ),
]});
