#
# This updates the current draft release notes when a PR is merged
#
name: Add to Release Notes
on:
  push:
    branches:
      - main
jobs:
  draft-release:
    runs-on: ubuntu-slim
    if: github.repository == 'sqlfluff/sqlfluff'
    steps:
    - name: Update release notes
      uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9  # v7.7.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
