name: Publish dbt templater PyPI Version

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 1

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true
          cache-dependency-glob: |
            requirements_dev.txt
            pyproject.toml
            constraints/*.txt

      - name: Install Dependencies
        run: |
          uv pip install --system --upgrade tox tox-uv

      - name: Build Distribution (dbt plugin)
        # tox commands run relative to the repo root.
        run: tox -e build-dist -- plugins/sqlfluff-templater-dbt

      - name: Copy builds to main dist folder
        # We move them here so that the github action can still access them
        run: cp -r plugins/sqlfluff-templater-dbt/dist/. dist/

      - name: Publish Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_DBT_TEMPLATER_TOKEN }}
          skip-existing: true
